language: c
os: linux

before_install:
  # Save path to the git respository
  - PROJECT_PATH=$(pwd)/example

install:
  # Install toolchain in opt folder
  - cd /opt
  - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
  - tar -xvf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
  # install SDK in opt folder
  - mkdir sdk
  - cd sdk
  - wget https://www.nordicsemi.com/-/media/Software-and-other-downloads/SDKs/nRF5/Binaries/nRF5SDK160098a08e2.zip
  - unzip nRF5SDK160098a08e2.zip
  # install nrfjprog
  - cd /opt
  - wget https://www.nordicsemi.com/-/media/Software-and-other-downloads/Desktop-software/nRF-command-line-tools/sw/Versions-10-x-x/10-8-0/nRFCommandLineTools1080Linuxamd64tar.gz
  - tar -xvf nRFCommandLineTools1080Linuxamd64tar.gz

script:
  - cd $PROJECT_PATH
  #cmake configure
  - cmake -DARM_NONE_EABI_TOOLCHAIN_PATH=/opt/gcc-arm-none-eabi-9-2019-q4-major -H. -B"cmake-build" -G "Unix Makefiles"
  #build
  - make -j
